"""create tables

Revision ID: 2538edfcbb60
Revises: 
Create Date: 2024-12-16 21:44:48.112077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2538edfcbb60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('dept_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.create_table('goods',
    sa.Column('good_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('producer', sa.String(), nullable=True),
    sa.Column('dept_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('good_id')
    )
    op.create_table('workers',
    sa.Column('worker_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('dept_id', sa.UUID(), nullable=True),
    sa.Column('information', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('worker_id')
    )
    op.create_table('sales',
    sa.Column('sale_id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('check_no', sa.Integer(), nullable=True),
    sa.Column('good_id', sa.UUID(), nullable=True),
    sa.Column('date_sale', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['good_id'], ['goods.good_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sale_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales')
    op.drop_table('workers')
    op.drop_table('goods')
    op.drop_table('departments')
    # ### end Alembic commands ###
